# Generated by Django 4.2.15 on 2024-08-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brigade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter", models.CharField(max_length=1)),
                (
                    "brigade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.brigade"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Platoon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("shift_hour_length", models.IntegerField()),
                (
                    "demanded_mos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.mos"
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.mission"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.position"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter", models.CharField(max_length=1)),
                (
                    "platoon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.platoon"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "brigade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.brigade"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.company"
                    ),
                ),
                (
                    "mos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.mos"
                    ),
                ),
                (
                    "platoon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.platoon"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.shift"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="team_leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_leader",
                to="myapp.user",
            ),
        ),
        migrations.AddField(
            model_name="platoon",
            name="commander",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platoon_commander",
                to="myapp.user",
            ),
        ),
        migrations.AddField(
            model_name="platoon",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.company"
            ),
        ),
        migrations.AddField(
            model_name="platoon",
            name="sargent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platoon_sargent",
                to="myapp.user",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="commander",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_commander",
                to="myapp.user",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="logistics_sargent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_logistics_sargent",
                to="myapp.user",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="second_commander",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_second_commander",
                to="myapp.user",
            ),
        ),
        migrations.AddField(
            model_name="brigade",
            name="commander",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brigade_commander",
                to="myapp.user",
            ),
        ),
        migrations.AddField(
            model_name="brigade",
            name="second_commander",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brigade_second_commander",
                to="myapp.user",
            ),
        ),
    ]
