# Generated by Django 4.2.15 on 2024-08-29 11:05

from django.db import migrations
def convert_personal_number_to_integer(apps, schema_editor):
    User = apps.get_model('myapp', 'User')
    counter = 0
    for user in User.objects.all():
        try:
            user.personal_number = int(user.personal_number)  # Convert to integer
            user.save()
        except ValueError:
            # Handle any cases where the conversion might fail
            # For example, you might want to set a default or raise an error
            user.personal_number = counter  # Set to a counter value for uniq value
            counter += 1
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_brigade_commander_alter_brigade_name_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_personal_number_to_integer),
    ]
