# Generated by Django 4.2.15 on 2024-08-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_convert_personal_number_to_integer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="personal_number",
            field=models.IntegerField(unique=True),
        ),
    ]
