# Generated by Django 4.2.15 on 2024-08-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_user_personal_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=123456, max_length=16),
            preserve_default=False,
        ),
    ]
