# Generated by Django 4.2.15 on 2024-09-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_user_available"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="NightwatchUser",),
    ]
