# Generated by Django 4.2.15 on 2024-09-03 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0009_rename_user_nightwatchuser"),
    ]

    operations = [
        migrations.RemoveField(model_name="nightwatchuser", name="email",),
        migrations.RemoveField(model_name="nightwatchuser", name="name",),
        migrations.RemoveField(model_name="nightwatchuser", name="password",),
        migrations.RemoveField(model_name="nightwatchuser", name="phone_number",),
        migrations.AddField(
            model_name="nightwatchuser",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
